sudo: required

# Installing Docker
services:
  - docker

script:
  # Testing if the docker is ready. 
  - echo "Testing works fine!"

after_success:
  # Build production docker images
  - docker build -t yourdockerusername/client ./client
  - docker build -t yourdockerusername/server ./server

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to the docker hub
  - docker push yourdockerusername/client
  - docker push yourdockerusername/server

deploy:
  # deploy to AWS Beanstalk
  provider: elasticbeanstalk
  region: ap-south-1
  app: your app name
  env: your ENV name of Beanstalk
  bucket_name: AWS S3 bucket name
  bucket_path: AWS S3 bucket path
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"